import { DefaultApi } from './endpoints/DefaultApi';
import { ApiKeyApi } from './endpoints/ApiKeyApi';
import { OrganizationApi } from './endpoints/OrganizationApi';
import { AnonymousApi } from './endpoints/AnonymousApi';
import { AdminApi } from './endpoints/AdminApi';
import { EmailOtpApi } from './endpoints/EmailOtpApi';
import { TwoFactorApi } from './endpoints/TwoFactorApi';
import { ProductsApi } from './endpoints/ProductsApi';
import { UsersApi } from './endpoints/UsersApi';
import { OrganizationsApi } from './endpoints/OrganizationsApi';
import { MembersApi } from './endpoints/MembersApi';
import { OrganizationInvitationsApi } from './endpoints/OrganizationInvitationsApi';
import { TicketsApi } from './endpoints/TicketsApi';
import { TicketMessagesApi } from './endpoints/TicketMessagesApi';
import { NotificationsApi } from './endpoints/NotificationsApi';
import { BlogApi } from './endpoints/BlogApi';
import { AssetsApi } from './endpoints/AssetsApi';
import { WaitlistApi } from './endpoints/WaitlistApi';
import { PaymentsApi } from './endpoints/PaymentsApi';
import { AppstoreApi } from './endpoints/AppstoreApi';
import { AppleApi } from './endpoints/AppleApi';
import { GoogleApi } from './endpoints/GoogleApi';
import { ReviewsApi } from './endpoints/ReviewsApi';
import { SyncApi } from './endpoints/SyncApi';
import { WebhooksApi } from './endpoints/WebhooksApi';
import { UnifiedApi } from './endpoints/UnifiedApi';
import { PlatformsApi } from './endpoints/PlatformsApi';
import { AnalyticsApi } from './endpoints/AnalyticsApi';
import { CustomersApi } from './endpoints/CustomersApi';
import { TransactionsApi } from './endpoints/TransactionsApi';
import { StatsApi } from './endpoints/StatsApi';
import { AiApi } from './endpoints/AiApi';
import { SubscriptionsApi } from './endpoints/SubscriptionsApi';
import { AttachmentsApi } from './endpoints/AttachmentsApi';
import type { ApiClientConfig } from './ApiClient';

export class ApiSDK {
  public defaultApi: DefaultApi;
  public apiKeyApi: ApiKeyApi;
  public organizationApi: OrganizationApi;
  public anonymousApi: AnonymousApi;
  public adminApi: AdminApi;
  public emailOtpApi: EmailOtpApi;
  public twoFactorApi: TwoFactorApi;
  public productsApi: ProductsApi;
  public usersApi: UsersApi;
  public organizationsApi: OrganizationsApi;
  public membersApi: MembersApi;
  public organizationInvitationsApi: OrganizationInvitationsApi;
  public ticketsApi: TicketsApi;
  public ticketMessagesApi: TicketMessagesApi;
  public notificationsApi: NotificationsApi;
  public blogApi: BlogApi;
  public assetsApi: AssetsApi;
  public waitlistApi: WaitlistApi;
  public paymentsApi: PaymentsApi;
  public appstoreApi: AppstoreApi;
  public appleApi: AppleApi;
  public googleApi: GoogleApi;
  public reviewsApi: ReviewsApi;
  public syncApi: SyncApi;
  public webhooksApi: WebhooksApi;
  public unifiedApi: UnifiedApi;
  public platformsApi: PlatformsApi;
  public analyticsApi: AnalyticsApi;
  public customersApi: CustomersApi;
  public transactionsApi: TransactionsApi;
  public statsApi: StatsApi;
  public aiApi: AiApi;
  public subscriptionsApi: SubscriptionsApi;
  public attachmentsApi: AttachmentsApi;

  constructor(config: ApiClientConfig) {
    this.defaultApi = new DefaultApi(config);
    this.apiKeyApi = new ApiKeyApi(config);
    this.organizationApi = new OrganizationApi(config);
    this.anonymousApi = new AnonymousApi(config);
    this.adminApi = new AdminApi(config);
    this.emailOtpApi = new EmailOtpApi(config);
    this.twoFactorApi = new TwoFactorApi(config);
    this.productsApi = new ProductsApi(config);
    this.usersApi = new UsersApi(config);
    this.organizationsApi = new OrganizationsApi(config);
    this.membersApi = new MembersApi(config);
    this.organizationInvitationsApi = new OrganizationInvitationsApi(config);
    this.ticketsApi = new TicketsApi(config);
    this.ticketMessagesApi = new TicketMessagesApi(config);
    this.notificationsApi = new NotificationsApi(config);
    this.blogApi = new BlogApi(config);
    this.assetsApi = new AssetsApi(config);
    this.waitlistApi = new WaitlistApi(config);
    this.paymentsApi = new PaymentsApi(config);
    this.appstoreApi = new AppstoreApi(config);
    this.appleApi = new AppleApi(config);
    this.googleApi = new GoogleApi(config);
    this.reviewsApi = new ReviewsApi(config);
    this.syncApi = new SyncApi(config);
    this.webhooksApi = new WebhooksApi(config);
    this.unifiedApi = new UnifiedApi(config);
    this.platformsApi = new PlatformsApi(config);
    this.analyticsApi = new AnalyticsApi(config);
    this.customersApi = new CustomersApi(config);
    this.transactionsApi = new TransactionsApi(config);
    this.statsApi = new StatsApi(config);
    this.aiApi = new AiApi(config);
    this.subscriptionsApi = new SubscriptionsApi(config);
    this.attachmentsApi = new AttachmentsApi(config);
  }
}
